site_name: chromatic
site_url: https://zkbt.github.com/chromatic
nav:
    # - Welcome: index.md
    # - installation.ipynb
    # - quickstart.ipynb
    # - User Guide:
    #     - basics.ipynb
    #     - io.ipynb
    #     - creating.ipynb
    #     - actions.ipynb
    #     - visualizing.ipynb
    #     - models.ipynb
    #     #- multi.ipynb
    # - Examples:
    #     - example-timeseries-spectra.ipynb
    # - Developer Guide:
    #     - designing.ipynb
    #     - documentation.ipynb
    #     - github.ipynb
    # - Related Tools:
    #     - tools/spectra.ipynb
    #     - tools/binning.ipynb
    #     - tools/colormaps.ipynb
    - Reference:
        - Rainbow-api.md
        - RainbowWithModel-api.md
theme:
  name: "material"
  features:
      - navigation.tracking
repo_url: https://github.com/zkbt/chromatic/
plugins:
  - search
  #- gen-files:
  #    scripts:
  #    - docs/generate_reference_pages.py  #
  # - mkdocs-jupyter:
  #     execute : True
  #     include_source : True
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          selection:
            docstring_style: "numpy"
          rendering:
            show_source: True
            show_root_heading: True
      custom_templates: templates
      watch:
        - chromatic
  - exclude:
      glob:
        - "example-datasets/*"
        - "*.pdf"
markdown_extensions:
    - toc:
        permalink: "#"





  #


# this is super borrowed from Christina Hedges' fabulous
# https://christinahedges.github.io/astronomy_workflow/
